aggregate: Person
apigateway: minos
apigateway_deploy: self-hosted
author: Collin M
broker: kafka
broker_deploy: self-hosted
database: postgres
deploy: docker-compose
description: People Service
discovery: minos
discovery_database: redis
discovery_deploy: self-hosted
email: collin@solublecode.dev
language: python
name: people
package_manager: poetry
postgres_deploy: self-hosted
project_deploy: docker-compose
project_description: Music streaming service
project_name: Spotify
project_version: 1.0.0
redis_deploy: self-hosted
template_name: project-init
template_registry: https://github.com/minos-framework/minos-templates/releases/download/v0.3.0
template_version: v0.3.0
version: 1.0.0
